### ISSUE TITLE
readlink -f and others don't exist on MacOS

### ISSUE THREAD

**Issue by tonin** [perfsonar/docker-devbox#3]
Used in `setup`.  Output from Big Sur (11.6.8) bash (5.1.16 from Homebrew):
```
$ ./setup --aliases
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

Some options to replace it are discussed at https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

And `getent` doesn't either:
```
docker-devbox/libexec/commands/boot: line 27: getent: command not found
```

**Comment by mfeit-internet2** [comment]
This is fixed; let me know if you have problems with it.
